// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIzaSyA8Hyc5siC45QM68CRjt1qKyUjCApXvYRo',
      appId: '1:1234567890:android:abcdef123456',
      messagingSenderId: '1234567890',
      projectId: 't2app-ff371',
      authDomain: 't2app-ff371.firebaseapp.com',
      databaseURL: 'https://t2app-ff371.firebaseio.com',
      storageBucket: 't2app-ff371.appspot.com',
      measurementId: 'G-ABCDEFGH1', // This value might not be present in all projects
    );
  }
}