// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf69jFQroQYtDhnndJ2OLgd7b9skanrGM',
    appId: '1:5289388645:web:3ade824ccda47db970348c',
    messagingSenderId: '5289388645',
    projectId: 'alskjdflawawheoeoa',
    authDomain: 'alskjdflawawheoeoa.firebaseapp.com',
    storageBucket: 'alskjdflawawheoeoa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdSsKoqM6A0M9XLimNHJpG0l5MqmmqbdM',
    appId: '1:5289388645:android:88266080886a366f70348c',
    messagingSenderId: '5289388645',
    projectId: 'alskjdflawawheoeoa',
    storageBucket: 'alskjdflawawheoeoa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCbHfiF6pPeDueMHejsCYnH2kNOT3Mq6Y',
    appId: '1:5289388645:ios:2c213684df00ab8e70348c',
    messagingSenderId: '5289388645',
    projectId: 'alskjdflawawheoeoa',
    storageBucket: 'alskjdflawawheoeoa.firebasestorage.app',
    androidClientId: '5289388645-8vpgu9e43s99l425b9u8q1ekskt1qosv.apps.googleusercontent.com',
    iosClientId: '5289388645-evjl1407f2o0ci13orv5sq5emrft1vmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.kaamHai',
  );
}
